# Generated by Django 5.1.3 on 2024-12-08 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_alter_room_options_remove_room_participants_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["-updated", "-created"]},
        ),
    ]
